#!/usr/bin/env node
// Turns reports/*.json into README.md and one page per repo.
// Run: node scripts/build.mjs

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { DETECTORS, TIERS } from '../lib/scan.mjs';

const ROOT = new URL('..', import.meta.url).pathname;
const R = ROOT + 'reports/';

const reports = readdirSync(R)
  .filter((f) => f.endsWith('.json'))
  .map((f) => JSON.parse(readFileSync(R + f, 'utf8')))
  .sort((a, b) => b.average_score - a.average_score || b.skill_count - a.skill_count);

const esc = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
const pct = (n, d) => (d ? Math.round((n / d) * 100) : 0);

function bar(dist, total) {
  const order = ['A', 'B', 'C', 'D', 'F'];
  return order
    .filter((g) => dist[g])
    .map((g) => `${g} ${dist[g]}`)
    .join(' · ');
}

// ---------------------------------------------------------------------------
// Per-repo page
// ---------------------------------------------------------------------------
function repoPage(r) {
  const out = [];
  out.push(`# ${r.name}`);
  out.push('');
  if (r.url) out.push(`Source: ${r.url}`);
  out.push('');
  out.push(
    `**${r.skill_count} skills · average ${r.average_score}/100 · scanned ${r.scanned_at} with scanner v${r.scanner_version}**`
  );
  out.push('');
  out.push(`Grades: ${bar(r.distribution, r.skill_count)}`);
  out.push('');
  out.push('## Capability profile');
  out.push('');
  out.push('| Tier | What it means | Skills |');
  out.push('| :-: | --- | --: |');
  for (const t of [0, 1, 2, 3, 4]) {
    out.push(`| T${t} ${TIERS[t].name} | ${TIERS[t].desc} | ${r.tiers[t] || 0} |`);
  }
  out.push('');

  if (Object.keys(r.by_detector).length) {
    out.push('## What fired');
    out.push('');
    out.push('| Detector | Skills | Share |');
    out.push('| --- | --: | --: |');
    for (const [id, n] of Object.entries(r.by_detector)) {
      out.push(`| \`${id}\` | ${n} | ${pct(n, r.skill_count)}% |`);
    }
    out.push('');
  }

  const notA = r.skills.filter((s) => s.grade !== 'A');
  out.push(`## Everything below an A (${notA.length})`);
  out.push('');
  if (!notA.length) {
    out.push('Nothing. Every skill in this repo scored an A.');
  }
  for (const s of notA) {
    out.push(`### ${s.grade} · ${s.score}/100 · \`${esc(s.name)}\``);
    out.push('');
    out.push(`\`${esc(s.path)}\` — tier ${s.tier} (${s.tier_name})`);
    if (s.description) out.push(`\n> ${esc(s.description)}`);
    out.push('');
    out.push('| Severity | Detector | Where | Context | Evidence |');
    out.push('| --- | --- | --- | --- | --- |');
    const seen = new Set();
    for (const f of s.findings) {
      if (f.rollup || f.severity === 'info') continue;
      const key = f.id + f.file;
      if (seen.has(key)) continue;
      seen.add(key);
      const sev = f.suppressed ? `~~${f.severity}~~` : `**${f.severity}**`;
      out.push(
        `| ${sev} | \`${f.id}\` | \`${esc(f.file)}:${f.line}\` | ${f.context} | \`${esc(
          (f.evidence || f.match).slice(0, 110)
        )}\` |`
      );
    }
    if (s.suppressed_count) {
      const reason = s.findings.find((f) => f.suppression_reason)?.suppression_reason;
      out.push('');
      out.push(`> **${s.suppressed_count} finding(s) suppressed.** ${esc(reason)}`);
    }
    out.push('');
  }
  out.push('');
  out.push('<sub>Generated by `scripts/build.mjs`. Do not edit directly.</sub>');
  return out.join('\n');
}

// ---------------------------------------------------------------------------
// README
// ---------------------------------------------------------------------------
function readme() {
  const totalSkills = reports.reduce((a, r) => a + r.skill_count, 0);
  const totalF = reports.reduce((a, r) => a + r.distribution.F, 0);
  const totalExec = reports.reduce((a, r) => a + (r.tiers[3] || 0) + (r.tiers[4] || 0), 0);

  const out = [];
  out.push('# skillrank');
  out.push('');
  out.push('**You installed forty agent skills. Do you know which ones can read your SSH key?**');
  out.push('');
  out.push(
    'There are at least seven competing directories of agent skills and a combined corpus in ' +
      'the thousands. Every one of them tells you what a skill *does*. None of them tells you ' +
      'what it *can do* — to your files, your credentials, and your machine. This is that layer.'
  );
  out.push('');
  out.push(
    `![repos](https://img.shields.io/badge/repos-${reports.length}-blue) ` +
      `![skills](https://img.shields.io/badge/skills%20scanned-${totalSkills.toLocaleString('en-US')}-blue) ` +
      `![exec](https://img.shields.io/badge/can%20run%20commands-${totalExec.toLocaleString('en-US')}-orange) ` +
      `![f](https://img.shields.io/badge/graded%20F-${totalF}-red) ` +
      '![cost](https://img.shields.io/badge/cost%20to%20run-%240.00-brightgreen)');
  out.push('');
  out.push('## Scan something right now');
  out.push('');
  out.push('```bash');
  out.push('npx skillrank ~/.claude/skills          # what you have already installed');
  out.push('npx skillrank ./some-skill-you-found    # before you install it');
  out.push('npx skillrank . --min B                 # exit 1 in CI if anything is worse than B');
  out.push('```');
  out.push('');
  out.push(
    'No API key. No account. No model call. **No tokens spent** — this is regex and file reads, ' +
      'which is a deliberate design constraint: the moment grading costs money per skill, ' +
      'coverage becomes a budget decision and the long tail never gets scanned. ' +
      `The ${totalSkills.toLocaleString('en-US')} skills below were graded in under five seconds for nothing.`
  );
  out.push('');
  out.push('## The leaderboard');
  out.push('');
  out.push('| Repo | Skills | Avg | Grades | Can run commands | Report |');
  out.push('| --- | --: | --: | --- | --: | --- |');
  for (const r of reports) {
    const exec = (r.tiers[3] || 0) + (r.tiers[4] || 0);
    const link = r.url ? `[${esc(r.name)}](${r.url})` : esc(r.name);
    out.push(
      `| ${link} | ${r.skill_count.toLocaleString('en-US')} | **${r.average_score}** | ${bar(
        r.distribution,
        r.skill_count
      )} | ${exec} (${pct(exec, r.skill_count)}%) | [details](reports/${r.slug}.md) |`
    );
  }
  out.push('');
  out.push('<sub>Average score, 0–100. A repo of harmless text formatters will beat a repo of deployment tools, and that is correct — the score measures blast radius, not quality.</sub>');
  out.push('');
  out.push('## Capability tiers');
  out.push('');
  out.push('The tier is not a judgement. A deployment skill *should* be T3. The tier exists so you can ask the useful question: **why does a changelog formatter need the network?**');
  out.push('');
  out.push('| Tier | Meaning |');
  out.push('| :-: | --- |');
  for (const t of [0, 1, 2, 3, 4]) out.push(`| **T${t} ${TIERS[t].name}** | ${TIERS[t].desc} |`);
  out.push('');
  out.push('## What it looks for');
  out.push('');
  out.push('| Detector | Severity | Why it matters |');
  out.push('| --- | :-: | --- |');
  for (const d of DETECTORS) out.push(`| \`${d.id}\` | ${d.severity} | ${esc(d.why)} |`);
  out.push('');
  out.push('Plus one combination rule: **reading credentials is fine, sending data is fine, doing both in one skill** is the shape of every credential stealer ever written, and costs an extra 35 points.');
  out.push('');
  out.push('## Why the grades are not harsher');
  out.push('');
  out.push(
    'The first version of this scanner graded every security skill in the corpus an **F** — because ' +
      'a skill that teaches you to spot `ignore previous instructions` necessarily contains the ' +
      'string `ignore previous instructions`. An antivirus that quarantines its own definitions ' +
      'file is not a strict antivirus, it is a broken one.'
  );
  out.push('');
  out.push('So the scanner reads context:');
  out.push('');
  out.push('- A pattern inside `` `backticks` `` is demoted one level — it is being named, not run.');
  out.push('- A quoted example of an injection string does not count against a skill that is documenting it.');
  out.push('- `curl http://localhost:3000/health` is not data exfiltration.');
  out.push('- `🧑‍💼` is built from U+200D ZERO WIDTH JOINER and is not a hidden-instruction attack.');
  out.push('- A hardcoded key in `assets/sample_codebase/` is a teaching aid.');
  out.push('- Vendored fonts, binaries and XML schemas are counted and reported as **unscanned**, not silently passed.');
  out.push('');
  out.push('Each of those is a fixture in `test/fixtures/` and a test in `scripts/test.mjs`, because every false positive we fix has to stay fixed. Run `node scripts/test.mjs`.');
  out.push('');
  out.push('## Honest limits');
  out.push('');
  out.push('Read this part before trusting a grade.');
  out.push('');
  out.push('- **An A means "no known pattern fired". It does not mean safe.** Novel phrasing, a payload behind a URL, or logic in a compiled binary will all pass.');
  out.push('- **Static analysis cannot read intent.** It cannot tell a threat catalogue from a runbook. That is what [`suppressions.yml`](suppressions.yml) is for — a public baseline where a human overrides the scanner, in the open, with a name and a reason attached. Suppressed findings are still shown, just not counted.');
  out.push('- **The score is blast radius, not quality.** A brilliant skill that needs shell access scores below a mediocre one that does not.');
  out.push('- **A skill can change after you install it.** These grades are a snapshot of a commit, and the fingerprint in each report tells you which one.');
  out.push('- **This is not a substitute for reading the skill.** It is a way to know which forty of your skills you can skip reading.');
  out.push('');
  out.push('## Add a repo');
  out.push('');
  out.push('Drop a file in `registry/`, open a PR, and CI clones and scans it on the next run. See [CONTRIBUTING.md](CONTRIBUTING.md).');
  out.push('');
  out.push('## Licence');
  out.push('');
  out.push('Code MIT, data CC0. If you are a maintainer and think a grade is wrong, open an issue — a wrong grade is a bug, and getting it wrong in public is how it gets fixed.');
  out.push('');
  out.push('<sub>Generated by `scripts/build.mjs`. Do not edit this file directly.</sub>');
  return out.join('\n');
}

for (const r of reports) writeFileSync(`${R}${r.slug}.md`, repoPage(r) + '\n');
writeFileSync(ROOT + 'README.md', readme() + '\n');
console.log(
  `✓ built README.md + ${reports.length} report pages — ${reports
    .reduce((a, r) => a + r.skill_count, 0)
    .toLocaleString('en-US')} skills`
);
